title: Gerald Stockinger
description: Technology, Data & Product
url: "https://datastrategy.services"
baseurl: ""

# Build
markdown: kramdown
permalink: /blog/:slug/

# Blog
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
